sudo: required
services:
  - docker

before_install:
  - docker build -t tpechacek/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true tpechacek/docker-react-test npm run test -- --coverage
